### ISSUE TITLE
RobotAssembler[TODO]

### ISSUE THREAD

**Issue by YoheiKakiuchi** [IRSL-tut/robot_assembler_plugin#2]
- [ ] マニュアルの作成
- [ ] バーのアイコン作る
- [ ] URDFファイルへの保存
- [x] next alignの簡単な方法 => key-eventへの対応
- [ ] un-align (attachしていないitemの再配置)
- [ ] undo
- [x] remove parts
- [ ] パーツ選択時のパーツが分かりやすく
  - [ ] 分かりやすい名前
  - [ ] イメージの追加
- [ ] connectの表示
  - [ ] 表示の選択 (point or actuator | active or in-active | hide)
  - [ ] scale導入 => パネルから選択できるように
  - [ ] 選択や状態に依存したgeometryの変更
- [ ] robot/partsの表示
  - [ ] 選択や状態に依存したgeometryの変更
- [ ] ConnectingConstraintSettings: の整合性チェック
  - [ ] allowed-configurationにreverseがあるかどうか->必要か？
  - [ ] matchのセッティングの定義を明確にする(親子関係によるcoordsの逆転をどうするか)
  - [ ] attachとconfigのサーチを分ける。。。
  - [ ] historyのconfigをcoordsのみにする
  - [ ] coords => configのリバースサーチを作る
- [ ] bodyのcontextメニュー()
- [ ] partsのcontextメニュー
- [ ] connectingのcontextメニュー
- [ ] View(パーツを作る)
  - [x] 色の指定
- [ ] AssemblerTree
  - [ ] labelに色付ける?
  - [x] sceneのclickの反映
- [ ] PartsView
  - [ ] パラメータ設定(string)
  - [ ] パラメータ設定(int, double)
  - [ ] パラメータ設定(coords)  
  - [ ] combo box(parts, connect, actuator, link)
- [ ] .roboasmファイルだけでパースする
- [ ] python binding
  - [ ] assembler
  - [ ] .roboasmファイルパース
  - [ ] GUI等
